osx_image: xcode9.4
dist: xenial

sudo: required

language: node_js
node_js: 'node'

os:
    - osx
    - linux
    - windows
    
addons:
    apt:
        packages:
            - xvfb

install:
    - npm ci
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    
script:
    - npm run make
