osx_image: xcode9.4
dist: xenial

sudo: required

language: node_js
node_js: 'node'

os:
    - osx
    - linux
    - windows
    
addons:
    apt:
        sources:
            - sourceline: 'ppa:alexlarsson/flatpak'
        packages:
            - xvfb
            - flatpak
            - flatpak-builder
            - elfutils
            
install:
    - if [ $TRAVIS_OS_NAME = linux ]; then sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo; sudo flatpak install -y org.freedesktop.Platform/x86_64/19.08 org.freedesktop.Sdk/x86_64/1.6 org.electronjs.Electron2.BaseApp/x86_64/stable; fi
    - npm ci
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    
env:
    - DEBUG="*"
    
script:
    - npm run make
