osx_image: xcode9.4
dist: xenial

language: node_js
node_js: 'node'

os:
    - osx
    - linux
    - windows
    
addons:
    apt:
        sources:
            - sourceline: 'ppa:alexlarsson/flatpak'
        packages:
            - xvfb
            - flatpak
            - flatpak-builder
            - elfutils
            
install:
    - if [ $TRAVIS_OS_NAME = linux ]; then
      sudo flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo;
      sudo flatpak --user install -y org.freedesktop.Platform/x86_64/19.08 org.freedesktop.Sdk/x86_64/19.08 org.electronjs.Electron2.BaseApp/x86_64/stable;
      flatpak install --user --no-deps --assumeyes --arch x86_64 --from https://raw.githubusercontent.com/endlessm/flatpak-bundler/master/refs/freedesktop-sdk-1.4.flatpakref;
      flatpak install --user --no-deps --assumeyes --arch x86_64 --from https://raw.githubusercontent.com/endlessm/flatpak-bundler/master/refs/freedesktop-runtime-1.4.flatpakref;
      flatpak install --user --no-deps --assumeyes --arch x86_64 --from https://s3-us-west-2.amazonaws.com/electron-flatpak.endlessm.com/electron-base-app-master.flatpakref;
      fi
    - npm ci
    
env:
    - DEBUG="*"
    
script:
    - npm run publish
