osx_image: xcode9.4
dist: xenial

sudo: required

language: node_js
node_js: 'node'

os:
    - osx
    - linux
    - windows
    
addons:
    apt:
        sources:
            - sourceline: 'ppa:alexlarsson/flatpak'
        
        packages:
            - xvfb
            - flatpak
            - flatpak-builder
            - elfutils

install:
    - npm ci
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    
env:
    - DEBUG="*"
    
script:
    - npm run make
