osx_image: xcode9.4
dist: xenial

language: node_js
node_js: 'node'

os:
    - osx
    - linux
    - windows
    
addons:
    apt:
        sources:
            - sourceline: 'ppa:alexlarsson/flatpak'
        packages:
            - xvfb
            - flatpak
            - flatpak-builder
            - elfutils
            
install:
    - if [ $TRAVIS_OS_NAME = linux ]; then
      flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo;
      flatpak --user install -y org.freedesktop.Platform/x86_64/19.08 org.freedesktop.Sdk/x86_64/19.08 org.electronjs.Electron2.BaseApp/x86_64/stable;
      fi
    - npm ci
    
env:
    - DEBUG="*"
    - BRANCH=${git branch --show-current}
    
script:
    - npm run make

before_deploy:
    - git config --local user.name "SFR"
    - git config --local user.email "git@sfr.moe"
    - git tag $BRANCH
deploy:
    provider: releases
    api_key: 
        secure: GITHUB_TOKEN
    file_glob: true
    file: out/**/*
    skip_cleanup: true
    draft: true
    overwrite: true
