name: "Assign Reviewer to Dependency PRs"
on:
  pull_request:
    types: [labeled]
    
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
    - uses: shufo/auto-assign-reviewer-by-issuer@v1.0.0
      with:
        config: '.github/reviewers.yml'
      if: contains(github.event.pull_request.labels.*.name, 'dependencies')
