name: Branch

on: push

jobs:
    linux:
        name: Linux
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - run: npm ci
            - run: npm run make
            - uses: actions/upload-artifact@v2
              with:
                  name: 'Stonecutter-linux'
                  path: 'out/stonecutter-electron-*'
    macos:
        name: macOS
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - run: npm ci
            - run: npm run make
              env: 
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - uses: actions/upload-artifact@v2
              with:
                  name: 'Stonecutter-macos'
                  path: 'out/Stonecutter-*.dmg'
    windows:
        name: Windows
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - run: npm ci
            - run: npm run make
              env: 
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - uses: actions/upload-artifact@v2
              with:
                  name: 'Stonecutter-win'
                  path: 'out/make/squirrel.windows/x64/*.exe'
