name: Pull Request

on: pull_request

jobs:
    linux:
        name: Linux
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - run: npm ci
            - run: npm run make
    macos:
        name: macOS
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - run: npm ci
            - run: npm run make
              env: 
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    windows:
        name: Windows
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - run: npm ci
            - run: npm run make
              env: 
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
